image: microsoft/dotnet:latest

stages:
    - build
    - test

before_script:
    - 'cd src/ci/'
 
build:pomodoro_api:
    stage: build
    script:
        - "sh build.sh pomodoro_api"
        
build:tasks_api:
    stage: build
    script:
        - "sh build.sh tasks_api"

test:pomodoro_api:
    stage: test
    script: 
        - "sh test.sh pomodoro_api"

test:tasks_api:
    stage: test
    script: 
        - "sh test.sh tasks_api"