image: microsoft/dotnet:latest

#variables:
    #OBJECTS_DIRECTORY: 'obj'
    #NUGET_PACKAGES_DIRECTORY: '.nuget'
    #SOURCE_CODE_PATH: '*/*/' 
    #//TODO: check it

stages:
    - build
    - test

#cache:
    #key: "$CI_JOB_STAGE-$CI_COMMIT_REF_SLUG"
    #paths:
        #- '$SOURCE_CODE_PATH$OBJECTS_DIRECTORY/project.assets.json'
        #- '$SOURCE_CODE_PATH$OBJECTS_DIRECTORY/*.csproj.nuget.*'
        #- '$NUGET_PACKAGES_DIRECTORY'
  
    #policy: pull-push
 
before_script:
    - 'cd src/ci'
 
build:pomodoro_api:
    stage: build
    script:
        - "build.sh pomodoro_api"
        
build:tasks_api:
    stage: build
    script:
        - "build.sh tasks_api"

test:pomodoro_api:
    stage: test
    script: 
        - "test.sh pomodoro_api"