image: microsoft/dotnet:latest

stages:
    - build
    - test
    - deploy

build:pomodoro_api:
    stage: build
    script:
        - curl https://img.shields.io/badge/Pomodoro.API-failed-red.svg --create-dirs -o public/badges/pomodoro_api_build.svg
        - sh src/ci/build.sh pomodoro_api
        - curl https://img.shields.io/badge/Pomodoro.API-succeeded-success.svg > public/badges/pomodoro_api_build.svg
    allow_failure: true
    artifacts:
        paths:
            - public/badges/pomodoro_api_build.svg
            
build:tasks_api:
    stage: build
    script:
        - curl https://img.shields.io/badge/Tasks.API-failed-red.svg > --create-dirs -o public/badges/tasks_api_build.svg
        - sh src/ci/build.sh tasks_api
        - curl https://img.shields.io/badge/Tasks.API-succeeded-success.svg > public/badges/tasks_api_build.svg
    allow_failure: true
    artifacts:
        paths:
            - public/badges/pomodoro_api_build.svg

test:pomodoro_api:
    stage: test
    script: 
        - sh src/ci/test.sh pomodoro_api

test:tasks_api:
    stage: test
    script: 
        - sh src/ci/test.sh tasks_api
        
pages:
  stage: deploy
  script:
    - echo "Deploying pages..."
  artifacts:
    paths:
      - public/
  only:
    - develop